# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, max_length=250, verbose_name='URL'),
        ),
    ]
